modLoader="javafml"
loaderVersion="[2,)"
license="Apache License version 2.0"

[[mods]]
modId="end_reimagined"
version="1.3.6"
displayName="End Reimagined"
displayURL="https://kaisoneo.kesug.com"
logoFile="logo.png"
credits="Kaisoneo"
authors="Kaisoneo"
description="You think The End ist Boring? Probelm Solved, with my End Reimagined Mod.  "

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.end_reimagined]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.end_reimagined]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.end_reimagined]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


[[mixins]]
    config="mixins.end_reimagined.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration